Pais.create!([
  {nombre: "Argentina"},
  {nombre: "Paraguay"},
  {nombre: "Brasil"}
])

Provincia.create!([
  {nombre: "Misiones", pais_id: 1},
  {nombre: "Corrientes", pais_id: 1},
  {nombre: "Itapúa", pais_id: 2},
  {nombre: "Bahia", pais_id: 3}
])

Ciudad.create!([
  {nombre: "Posadas", provincia_id: 1, pais_id: 1},
  {nombre: "Apostoles", provincia_id: 1, pais_id: 1},
  {nombre: "Bella Vista", provincia_id: 2, pais_id: 1},
  {nombre: "Encarnación", provincia_id: 3, pais_id: 2}
])

Area.create!([
  {nombre: "Urbana"},
  {nombre: "Rural"}
])

TipoDocumento.create!([
  {nombre: "DNI"},
  {nombre: "Libreta de Enrolamiento"}
])

Departamento.create!([
  {nombre: "Finanzas"},
  {nombre: "Recursos Humanos"},
  {nombre: "Evaluación"},
  {nombre: "Logística"},
  {nombre: "Dirección"}
])

RolDeEmpleado.create!([
  {nombre: "Encargado de nómina", departamento_id: 1},
  {nombre: "Encargado de recaudaciones e ingresos", departamento_id: 1},
  {nombre: "Jefe de Recursos Humanos", departamento_id: 2},
  {nombre: "Jefe de mercadeo", departamento_id: 3},
  {nombre: "jefe de producción", departamento_id: 3},
  {nombre: "Investigación y desarrollo", departamento_id: 4},
  {nombre: "Capacitación - Mentoring", departamento_id: 4},
  {nombre: "Director General", departamento_id: 5}
])

Empleado.create!([
  {codigo: "EMP-001", nombre: "Ana", apellido: "Canteros", nroIdentificacion: "36063076", fechaNacimiento: "1991-11-05", calle: "176", nroDomicilio: "7141", piso: "", dpto: "", telefono: "4401604", email: "valeriianaa@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 5, area_id: 1, rol_de_empleado_id: 8},
  {codigo: "EMP-002", nombre: "Martina", apellido: "Quiñones", nroIdentificacion: "25147001", fechaNacimiento: "1974-05-06", calle: "Tereré", nroDomicilio: "7302", piso: "4", dpto: "B", telefono: "4355987", email: "martinaquinones@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 4, area_id: 1, rol_de_empleado_id: 7},
  {codigo: "EMP-003", nombre: "Alba", apellido: "Perez", nroIdentificacion: "33880657", fechaNacimiento: "1986-10-17", calle: "Rivera", nroDomicilio: "6872", piso: "", dpto: "", telefono: "459885", email: "albaperez@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 3, area_id: 1, rol_de_empleado_id: 4},
  {codigo: "EMP-004", nombre: "Victor", apellido: "Vazquez Valdez", nroIdentificacion: "33988307", fechaNacimiento: "1987-01-21", calle: "Tereré", nroDomicilio: "1187", piso: "", dpto: "", telefono: "4456980", email: "vvv@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 2, area_id: 1, rol_de_empleado_id: 3},
  {codigo: "EMP-005", nombre: "Zoe", apellido: "Cyr", nroIdentificacion: "38187849", fechaNacimiento: "1995-06-08", calle: "Castilla", nroDomicilio: "8299", piso: "10", dpto: "15", telefono: "4444176", email: "zoecyr@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 1, area_id: 1, rol_de_empleado_id: 2},
  {codigo: "EMP-006", nombre: "Luis", apellido: "Castro", nroIdentificacion: "22617493", fechaNacimiento: "1970-02-20", calle: "Av. Andalucia", nroDomicilio: "7415", piso: "12", dpto: "A", telefono: "4255987", email: "luiscastro@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 4, area_id: 1, rol_de_empleado_id: 7},
  {codigo: "EMP-007", nombre: "Maria", apellido: "Gonzalez", nroIdentificacion: "36134076", fechaNacimiento: "1991-11-05", calle: "176", nroDomicilio: "7141", piso: "", dpto: "", telefono: "4401604", email: "mg@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 5, area_id: 1, rol_de_empleado_id: 8},
  {codigo: "EMP-008", nombre: "Elena", apellido: "Ceballos", nroIdentificacion: "25198461", fechaNacimiento: "1974-05-06", calle: "Tereré", nroDomicilio: "7302", piso: "4", dpto: "B", telefono: "4355987", email: "ec@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 4, area_id: 1, rol_de_empleado_id: 7},
  {codigo: "EMP-009", nombre: "Alberto", apellido: "Padilla", nroIdentificacion: "33843657", fechaNacimiento: "1986-10-17", calle: "Rivera", nroDomicilio: "6872", piso: "", dpto: "", telefono: "459885", email: "ap@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 3, area_id: 1, rol_de_empleado_id: 4},
  {codigo: "EMP-010", nombre: "Fernando", apellido: "Gonzalez", nroIdentificacion: "33980912", fechaNacimiento: "1987-01-21", calle: "Tereré", nroDomicilio: "1187", piso: "", dpto: "", telefono: "4456980", email: "fg@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 2, area_id: 1, rol_de_empleado_id: 3},
  {codigo: "EMP-011", nombre: "Tiago", apellido: "Gonzalez", nroIdentificacion: "38187222", fechaNacimiento: "1995-06-08", calle: "Castilla", nroDomicilio: "8299", piso: "10", dpto: "15", telefono: "4444176", email: "tiagogonzales@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 1, area_id: 1, rol_de_empleado_id: 2},
  {codigo: "EMP-012", nombre: "Cintia", apellido: "Castro", nroIdentificacion: "22612413", fechaNacimiento: "1970-02-20", calle: "Av. Andalucia", nroDomicilio: "7415", piso: "12", dpto: "A", telefono: "4255987", email: "cintiacastro@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 4, area_id: 1, rol_de_empleado_id: 7},
  {codigo: "EMP-013", nombre: "Josefina", apellido: "Jardin", nroIdentificacion: "36025176", fechaNacimiento: "1991-11-05", calle: "176", nroDomicilio: "7141", piso: "", dpto: "", telefono: "4401604", email: "josefinajardin@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 5, area_id: 1, rol_de_empleado_id: 8},
  {codigo: "EMP-014", nombre: "Diana", apellido: "Rivas", nroIdentificacion: "25948001", fechaNacimiento: "1974-05-06", calle: "Tereré", nroDomicilio: "7302", piso: "4", dpto: "B", telefono: "4355987", email: "dianarivas@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 4, area_id: 1, rol_de_empleado_id: 7},
  {codigo: "EMP-015", nombre: "Dario", apellido: "Gonzalez", nroIdentificacion: "33880019", fechaNacimiento: "1986-10-17", calle: "Rivera", nroDomicilio: "6872", piso: "", dpto: "", telefono: "459885", email: "dariogonzalez@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 3, area_id: 1, rol_de_empleado_id: 4},
  {codigo: "EMP-016", nombre: "Ciro", apellido: "Zamora", nroIdentificacion: "33983707", fechaNacimiento: "1987-01-21", calle: "Tereré", nroDomicilio: "1187", piso: "", dpto: "", telefono: "4456980", email: "cirozamora@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 2, area_id: 1, rol_de_empleado_id: 3},
  {codigo: "EMP-017", nombre: "Zoe", apellido: "Vazquez", nroIdentificacion: "3818104", fechaNacimiento: "1995-06-08", calle: "Castilla", nroDomicilio: "8299", piso: "10", dpto: "15", telefono: "4444176", email: "zoevazquez@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 1, area_id: 1, rol_de_empleado_id: 2},
  {codigo: "EMP-018", nombre: "Cristian", apellido: "Gonzalez", nroIdentificacion: "22659193", fechaNacimiento: "1970-02-20", calle: "Av. Andalucia", nroDomicilio: "7415", piso: "12", dpto: "A", telefono: "4255987", email: "cristiangonzalez@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 4, area_id: 1, rol_de_empleado_id: 7},
  {codigo: "EMP-019", nombre: "Ana", apellido: "Manfrin", nroIdentificacion: "36222076", fechaNacimiento: "1991-11-05", calle: "176", nroDomicilio: "7141", piso: "", dpto: "", telefono: "4401604", email: "anamanfrin@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 5, area_id: 1, rol_de_empleado_id: 8},
  {codigo: "EMP-020", nombre: "Martina", apellido: "Adamo", nroIdentificacion: "25841001", fechaNacimiento: "1974-05-06", calle: "Tereré", nroDomicilio: "7302", piso: "4", dpto: "B", telefono: "4355987", email: "martinaadamo@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 4, area_id: 1, rol_de_empleado_id: 7},
  {codigo: "EMP-021", nombre: "Roberto", apellido: "Milani", nroIdentificacion: "33880333", fechaNacimiento: "1986-10-17", calle: "Rivera", nroDomicilio: "6872", piso: "", dpto: "", telefono: "459885", email: "robertomilani@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 3, area_id: 1, rol_de_empleado_id: 4},
  {codigo: "EMP-022", nombre: "Victor", apellido: "Gonzalez", nroIdentificacion: "33984447", fechaNacimiento: "1987-01-21", calle: "Tereré", nroDomicilio: "1187", piso: "", dpto: "", telefono: "4456980", email: "victorgonzalez@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 2, area_id: 1, rol_de_empleado_id: 3},
  {codigo: "EMP-023", nombre: "Alejandro", apellido: "Cambril", nroIdentificacion: "38113409", fechaNacimiento: "1995-06-08", calle: "Castilla", nroDomicilio: "8299", piso: "10", dpto: "15", telefono: "4444176", email: "alejandrocambril@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 1, area_id: 1, rol_de_empleado_id: 2},
  {codigo: "EMP-024", nombre: "Luis", apellido: "Rizzo", nroIdentificacion: "22543493", fechaNacimiento: "1970-02-20", calle: "Av. Andalucia", nroDomicilio: "7415", piso: "12", dpto: "A", telefono: "4255987", email: "luisrizzo@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 4, area_id: 1, rol_de_empleado_id: 7},
  {codigo: "EMP-025", nombre: "Mario", apellido: "Rosas", nroIdentificacion: "36060986", fechaNacimiento: "1991-11-05", calle: "176", nroDomicilio: "7141", piso: "", dpto: "", telefono: "4401604", email: "mariorosas@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 5, area_id: 1, rol_de_empleado_id: 8},
  {codigo: "EMP-026", nombre: "Analia", apellido: "Granados", nroIdentificacion: "25131701", fechaNacimiento: "1974-05-06", calle: "Tereré", nroDomicilio: "7302", piso: "4", dpto: "B", telefono: "4355987", email: "analiagranados@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 4, area_id: 1, rol_de_empleado_id: 7},
  {codigo: "EMP-027", nombre: "Leonor", apellido: "Gonzalez", nroIdentificacion: "33888717", fechaNacimiento: "1986-10-17", calle: "Rivera", nroDomicilio: "6872", piso: "", dpto: "", telefono: "459885", email: "leonorgonzalez@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 3, area_id: 1, rol_de_empleado_id: 4},
  {codigo: "EMP-028", nombre: "Victor", apellido: "Baresi", nroIdentificacion: "33928407", fechaNacimiento: "1987-01-21", calle: "Tereré", nroDomicilio: "1187", piso: "", dpto: "", telefono: "4456980", email: "victorbaresi@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 2, area_id: 1, rol_de_empleado_id: 3},
  {codigo: "EMP-029", nombre: "Silvana", apellido: "Lazzaga", nroIdentificacion: "38918849", fechaNacimiento: "1995-06-08", calle: "Castilla", nroDomicilio: "8299", piso: "10", dpto: "15", telefono: "4444176", email: "silvanalazzaga@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 1, area_id: 1, rol_de_empleado_id: 2},
  {codigo: "EMP-030", nombre: "Juana", apellido: "Calabrese", nroIdentificacion: "220192493", fechaNacimiento: "1970-02-20", calle: "Av. Andalucia", nroDomicilio: "7415", piso: "12", dpto: "A", telefono: "4255987", email: "janacalabrese@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 4, area_id: 1, rol_de_empleado_id: 7},
  {codigo: "EMP-031", nombre: "Juliana", apellido: "Lombardi", nroIdentificacion: "38613849", fechaNacimiento: "1995-06-08", calle: "Castilla", nroDomicilio: "8299", piso: "10", dpto: "15", telefono: "4444176", email: "julianalombardi@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 1, area_id: 1, rol_de_empleado_id: 2},
  {codigo: "EMP-032", nombre: "Enrique", apellido: "Cano", nroIdentificacion: "22451493", fechaNacimiento: "1970-02-20", calle: "Av. Andalucia", nroDomicilio: "7415", piso: "12", dpto: "A", telefono: "4255987", email: "enriquecano@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 4, area_id: 1, rol_de_empleado_id: 7},
  {codigo: "EMP-033", nombre: "Gilda", apellido: "Lombarde", nroIdentificacion: "36064356", fechaNacimiento: "1991-11-05", calle: "176", nroDomicilio: "7141", piso: "", dpto: "", telefono: "4401604", email: "gildalombarde@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 5, area_id: 1, rol_de_empleado_id: 8},
  {codigo: "EMP-034", nombre: "Martin", apellido: "Bande", nroIdentificacion: "25124501", fechaNacimiento: "1974-05-06", calle: "Tereré", nroDomicilio: "7302", piso: "4", dpto: "B", telefono: "4355987", email: "martinbande@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 4, area_id: 1, rol_de_empleado_id: 7},
  {codigo: "EMP-035", nombre: "Gabriel", apellido: "Ferruccio", nroIdentificacion: "33451657", fechaNacimiento: "1986-10-17", calle: "Rivera", nroDomicilio: "6872", piso: "", dpto: "", telefono: "459885", email: "gabrielferuccio@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 3, area_id: 1, rol_de_empleado_id: 4},
  {codigo: "EMP-036", nombre: "Juan", apellido: "Mazzanti", nroIdentificacion: "33956107", fechaNacimiento: "1987-01-21", calle: "Tereré", nroDomicilio: "1187", piso: "", dpto: "", telefono: "4456980", email: "juanmazzanti@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 2, area_id: 1, rol_de_empleado_id: 3},
  {codigo: "EMP-037", nombre: "Karina", apellido: "Fiorentino", nroIdentificacion: "38663849", fechaNacimiento: "1995-06-08", calle: "Castilla", nroDomicilio: "8299", piso: "10", dpto: "15", telefono: "4444176", email: "karinafiorentino@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 1, area_id: 1, rol_de_empleado_id: 2},
  {codigo: "EMP-038", nombre: "Osvaldo", apellido: "Pagnotto", nroIdentificacion: "22019493", fechaNacimiento: "1970-02-20", calle: "Av. Andalucia", nroDomicilio: "7415", piso: "12", dpto: "A", telefono: "4255987", email: "osvaldopagnotto@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 4, area_id: 1, rol_de_empleado_id: 7},
  {codigo: "EMP-039", nombre: "Margarita", apellido: "Giordano", nroIdentificacion: "36068886", fechaNacimiento: "1991-11-05", calle: "176", nroDomicilio: "7141", piso: "", dpto: "", telefono: "4401604", email: "margaritagiordano@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 5, area_id: 1, rol_de_empleado_id: 8},
  {codigo: "EMP-040", nombre: "Rosa", apellido: "Napolitano", nroIdentificacion: "2576401", fechaNacimiento: "1974-05-06", calle: "Tereré", nroDomicilio: "7302", piso: "4", dpto: "B", telefono: "4355987", email: "rosanapolitano@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 4, area_id: 1, rol_de_empleado_id: 7},
  {codigo: "EMP-041", nombre: "Magdalena", apellido: "Bruno", nroIdentificacion: "38817849", fechaNacimiento: "1995-06-08", calle: "Castilla", nroDomicilio: "8299", piso: "10", dpto: "15", telefono: "4444176", email: "mardalenabruno@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 1, area_id: 1, rol_de_empleado_id: 2},
  {codigo: "EMP-042", nombre: "Mauricio", apellido: "Costa", nroIdentificacion: "22755493", fechaNacimiento: "1970-02-20", calle: "Av. Andalucia", nroDomicilio: "7415", piso: "12", dpto: "A", telefono: "4255987", email: "mauriciocosta@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 4, area_id: 1, rol_de_empleado_id: 7},
  {codigo: "EMP-043", nombre: "Ivan", apellido: "Costas", nroIdentificacion: "36755076", fechaNacimiento: "1991-11-05", calle: "176", nroDomicilio: "7141", piso: "", dpto: "", telefono: "4401604", email: "ivancostas@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 5, area_id: 1, rol_de_empleado_id: 8},
  {codigo: "EMP-044", nombre: "Pablo", apellido: "Davide", nroIdentificacion: "251934401", fechaNacimiento: "1974-05-06", calle: "Tereré", nroDomicilio: "7302", piso: "4", dpto: "B", telefono: "4355987", email: "pablodavide@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 4, area_id: 1, rol_de_empleado_id: 7},
  {codigo: "EMP-045", nombre: "Nicolas", apellido: "Medina", nroIdentificacion: "33801927", fechaNacimiento: "1986-10-17", calle: "Rivera", nroDomicilio: "6872", piso: "", dpto: "", telefono: "459885", email: "nicolasmedina@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 3, area_id: 1, rol_de_empleado_id: 4},
  {codigo: "EMP-046", nombre: "Celeste", apellido: "Milano", nroIdentificacion: "35122307", fechaNacimiento: "1987-01-21", calle: "Tereré", nroDomicilio: "1187", piso: "", dpto: "", telefono: "4456980", email: "celestemilano@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 2, area_id: 1, rol_de_empleado_id: 3},
  {codigo: "EMP-047", nombre: "Sebastian", apellido: "Schiavone", nroIdentificacion: "38175649", fechaNacimiento: "1995-06-08", calle: "Castilla", nroDomicilio: "8299", piso: "10", dpto: "15", telefono: "4444176", email: "sebastianschiavone@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 1, area_id: 1, rol_de_empleado_id: 2},
  {codigo: "EMP-048", nombre: "Ruben", apellido: "Almedina", nroIdentificacion: "22891493", fechaNacimiento: "1970-02-20", calle: "Av. Andalucia", nroDomicilio: "7415", piso: "12", dpto: "A", telefono: "4255987", email: "rubenalmedina@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 4, area_id: 1, rol_de_empleado_id: 7},
  {codigo: "EMP-049", nombre: "Cristian", apellido: "Camiño", nroIdentificacion: "36093716", fechaNacimiento: "1991-11-05", calle: "176", nroDomicilio: "7141", piso: "", dpto: "", telefono: "4401604", email: "cristiancamiño@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 5, area_id: 1, rol_de_empleado_id: 8},
  {codigo: "EMP-050", nombre: "Monica", apellido: "Conti", nroIdentificacion: "25888001", fechaNacimiento: "1974-05-06", calle: "Tereré", nroDomicilio: "7302", piso: "4", dpto: "B", telefono: "4355987", email: "monicaconti@gmail.com", type: "Empleado", pais_id: 1, provincia_id: 1, ciudad_id: 1, tipo_documento_id: 1, departamento_id: 4, area_id: 1, rol_de_empleado_id: 7}
])

Etapa.create!([
  {nombre: "Pre incubacion", descripcion: "-", etapaAnterior: nil},
  {nombre: "Incubación", descripcion: "-", etapaAnterior: 1},
  {nombre: "post incubacion", descripcion: "-", etapaAnterior: 2},
  {nombre: "Cuarta etapa", descripcion: "-", etapaAnterior: nil}
])

Actividad.create!([
  {nombre: "Presentación de la idea", descripcion: "Nombre de la idea de emprendimiento y breve descripción", obligatorio: true, actividades_antecedentes: [], etapa_id: 1},
  {nombre: "Análisis de factibilidad", descripcion: "Analisis de la factibilidad del emprendimiento es sus tres factores: económico, técnico y operativo", obligatorio: true, actividades_antecedentes: ["1"], etapa_id: 1},
  {nombre: "Evaluación", descripcion: "Los expertos de la incubadora evaluarán el proyecto presentado en base a lo desarrollado en los pasos anteriores. Los proyectos aprobados pasarán a la siguiente etapa", obligatorio: true, actividades_antecedentes: ["1", "2"], etapa_id: 1},
  {nombre: "Definicion del producto", descripcion: "El proyecto define en detalle cual será su actividad economica principal, qué y cómo es ese producto o servicio que desea comercializar", obligatorio: true, actividades_antecedentes: nil, etapa_id: 2},
  {nombre: "Misión, Visión, Objetivos", descripcion: "Definicion de misión, visión, y objetivos generales y particulares del emprendimiento", obligatorio: false, actividades_antecedentes: ["4"], etapa_id: 2},
  {nombre: "Mercado - Clientes principales", descripcion: "Definicion del nicho de mercado", obligatorio: true, actividades_antecedentes: ["4"], etapa_id: 2},
  {nombre: "Búsqueda de financiamiento", descripcion: "Ponerse en contacto con personas que ayudarán al crecimiento del proyecto", obligatorio: false, actividades_antecedentes: nil, etapa_id: 2},
  {nombre: "Asistencia a Conferencias", descripcion: "Cada emprendimiento debe asistir a por lo menos un evento que organice la empresa", obligatorio: true, actividades_antecedentes: nil, etapa_id: 2},
  {nombre: "Seguimiento", descripcion: "Empresa en etapa de post incubacion", obligatorio: true, actividades_antecedentes: nil, etapa_id: 3},
  {nombre: "Desarrollo de evento o conferencia", descripcion: "Los proyectos que lleguen a esta etapa deben dar charlas u organizar eventos para los nuevos emprendimientos en incubación", obligatorio: true, actividades_antecedentes: ["9"], etapa_id: 3},
  {nombre: "Financiamiento a un nuevo proyecto", descripcion: "Los proyectos que lleguen a esta etapa deben de poder financiar a otros emprendimientos emergentes o proveerles algun servicio que ayude a su crecimiento", obligatorio: true, actividades_antecedentes: ["9", "10"], etapa_id: 3}
])

Accion.create!([
  {nombre: "Crear", key_name: "create"},
  {nombre: "Eliminar", key_name: "destroy"},
  {nombre: "Ver", key_name: "show"},
  {nombre: "Index", key_name: "index"},
  {nombre: "Restringir acciones de acuerdo al tipo de persona", key_name: "by_persona_type"},
  {nombre: "Editar", key_name: "update"},
  {nombre: "Estadisticas", key_name: "estadistica"}
])

Modelo.create!([
  {nombre: "Actividad"},
  {nombre: "Area"},
  {nombre: "Ciudad"},
  {nombre: "ConceptoDePago"},
  {nombre: "Contacto"},
  {nombre: "Contrato"},
  {nombre: "Cuenta"},
  {nombre: "Departamento"},
  {nombre: "Descuento"},
  {nombre: "Empleado"},
  {nombre: "EspecialidadDeContacto"},
  {nombre: "Estado"},
  {nombre: "Etapa"},
  {nombre: "Evento"},
  {nombre: "EventoProyecto"},
  {nombre: "MiembroEquipo"},
  {nombre: "Pago"},
  {nombre: "Pais"},
  {nombre: "Provincia"},
  {nombre: "Proyecto"},
  {nombre: "Rol"},
  {nombre: "RolDeEmpleado"},
  {nombre: "TipoDocumento"},
  {nombre: "TipoDePago"},
  {nombre: "User"},
  {nombre: "ActividadProyecto"},
  {nombre: "CuotaPorCliente"}
])

Permiso.create!([
  {accion_id: 1, modelo_id: 1},
  {accion_id: 2, modelo_id: 1},
  {accion_id: 3, modelo_id: 1},
  {accion_id: 4, modelo_id: 1},
  {accion_id: 1, modelo_id: 2},
  {accion_id: 2, modelo_id: 2},
  {accion_id: 3, modelo_id: 2},
  {accion_id: 4, modelo_id: 2},
  {accion_id: 1, modelo_id: 3},
  {accion_id: 2, modelo_id: 3},
  {accion_id: 3, modelo_id: 3},
  {accion_id: 4, modelo_id: 3},
  {accion_id: 1, modelo_id: 4},
  {accion_id: 2, modelo_id: 4},
  {accion_id: 3, modelo_id: 4},
  {accion_id: 4, modelo_id: 4},
  {accion_id: 1, modelo_id: 5},
  {accion_id: 2, modelo_id: 5},
  {accion_id: 3, modelo_id: 5},
  {accion_id: 4, modelo_id: 5},
  {accion_id: 1, modelo_id: 6},
  {accion_id: 2, modelo_id: 6},
  {accion_id: 3, modelo_id: 6},
  {accion_id: 4, modelo_id: 6},
  {accion_id: 1, modelo_id: 7},
  {accion_id: 2, modelo_id: 7},
  {accion_id: 3, modelo_id: 7},
  {accion_id: 4, modelo_id: 7},
  {accion_id: 1, modelo_id: 8},
  {accion_id: 2, modelo_id: 8},
  {accion_id: 3, modelo_id: 8},
  {accion_id: 4, modelo_id: 8},
  {accion_id: 1, modelo_id: 9},
  {accion_id: 2, modelo_id: 9},
  {accion_id: 3, modelo_id: 9},
  {accion_id: 4, modelo_id: 9},
  {accion_id: 1, modelo_id: 10},
  {accion_id: 2, modelo_id: 10},
  {accion_id: 3, modelo_id: 10},
  {accion_id: 4, modelo_id: 10},
  {accion_id: 1, modelo_id: 11},
  {accion_id: 2, modelo_id: 11},
  {accion_id: 3, modelo_id: 11},
  {accion_id: 4, modelo_id: 11},
  {accion_id: 1, modelo_id: 12},
  {accion_id: 2, modelo_id: 12},
  {accion_id: 3, modelo_id: 12},
  {accion_id: 4, modelo_id: 12},
  {accion_id: 1, modelo_id: 13},
  {accion_id: 2, modelo_id: 13},
  {accion_id: 3, modelo_id: 13},
  {accion_id: 4, modelo_id: 13},
  {accion_id: 1, modelo_id: 14},
  {accion_id: 2, modelo_id: 14},
  {accion_id: 3, modelo_id: 14},
  {accion_id: 4, modelo_id: 14},
  {accion_id: 1, modelo_id: 15},
  {accion_id: 2, modelo_id: 15},
  {accion_id: 3, modelo_id: 15},
  {accion_id: 4, modelo_id: 15},
  {accion_id: 1, modelo_id: 16},
  {accion_id: 2, modelo_id: 16},
  {accion_id: 3, modelo_id: 16},
  {accion_id: 4, modelo_id: 16},
  {accion_id: 1, modelo_id: 17},
  {accion_id: 2, modelo_id: 17},
  {accion_id: 3, modelo_id: 17},
  {accion_id: 4, modelo_id: 17},
  {accion_id: 1, modelo_id: 18},
  {accion_id: 2, modelo_id: 18},
  {accion_id: 3, modelo_id: 18},
  {accion_id: 4, modelo_id: 18},
  {accion_id: 1, modelo_id: 19},
  {accion_id: 2, modelo_id: 19},
  {accion_id: 3, modelo_id: 19},
  {accion_id: 4, modelo_id: 19},
  {accion_id: 1, modelo_id: 20},
  {accion_id: 2, modelo_id: 20},
  {accion_id: 3, modelo_id: 20},
  {accion_id: 4, modelo_id: 20},
  {accion_id: 1, modelo_id: 21},
  {accion_id: 2, modelo_id: 21},
  {accion_id: 3, modelo_id: 21},
  {accion_id: 4, modelo_id: 21},
  {accion_id: 1, modelo_id: 22},
  {accion_id: 2, modelo_id: 22},
  {accion_id: 3, modelo_id: 22},
  {accion_id: 4, modelo_id: 22},
  {accion_id: 1, modelo_id: 23},
  {accion_id: 2, modelo_id: 23},
  {accion_id: 3, modelo_id: 23},
  {accion_id: 4, modelo_id: 23},
  {accion_id: 1, modelo_id: 24},
  {accion_id: 2, modelo_id: 24},
  {accion_id: 3, modelo_id: 24},
  {accion_id: 4, modelo_id: 24},
  {accion_id: 1, modelo_id: 25},
  {accion_id: 2, modelo_id: 25},
  {accion_id: 3, modelo_id: 25},
  {accion_id: 4, modelo_id: 25},
  {accion_id: 5, modelo_id: 20},
  {accion_id: 6, modelo_id: 1},
  {accion_id: 6, modelo_id: 2},
  {accion_id: 6, modelo_id: 3},
  {accion_id: 6, modelo_id: 4},
  {accion_id: 6, modelo_id: 5},
  {accion_id: 6, modelo_id: 6},
  {accion_id: 6, modelo_id: 7},
  {accion_id: 6, modelo_id: 8},
  {accion_id: 6, modelo_id: 9},
  {accion_id: 6, modelo_id: 10},
  {accion_id: 6, modelo_id: 11},
  {accion_id: 6, modelo_id: 12},
  {accion_id: 6, modelo_id: 13},
  {accion_id: 6, modelo_id: 14},
  {accion_id: 6, modelo_id: 15},
  {accion_id: 6, modelo_id: 16},
  {accion_id: 6, modelo_id: 17},
  {accion_id: 6, modelo_id: 18},
  {accion_id: 6, modelo_id: 19},
  {accion_id: 6, modelo_id: 20},
  {accion_id: 6, modelo_id: 21},
  {accion_id: 6, modelo_id: 22},
  {accion_id: 6, modelo_id: 23},
  {accion_id: 6, modelo_id: 24},
  {accion_id: 6, modelo_id: 25},
  {accion_id: 2, modelo_id: 26},
  {accion_id: 4, modelo_id: 26},
  {accion_id: 6, modelo_id: 26},
  {accion_id: 5, modelo_id: 17},
  {accion_id: 5, modelo_id: 14},
  {accion_id: 5, modelo_id: 6},
  {accion_id: 1, modelo_id: 27},
  {accion_id: 3, modelo_id: 27},
  {accion_id: 4, modelo_id: 27},
  {accion_id: 5, modelo_id: 27},
  {accion_id: 6, modelo_id: 27},
  {accion_id: 7, modelo_id: 20}
])

Rol.create!([
  {nombre: "admin_empleados"},
  {nombre: "super_admin"},
  {nombre: "Encargado de Proyectos (mentor)"},
  {nombre: "Miembro de Equipo"}
])

Rol::HABTM_Permisos.create!([
  {permiso_id: 77, rol_id: 3},
  {permiso_id: 78, rol_id: 3},
  {permiso_id: 79, rol_id: 3},
  {permiso_id: 80, rol_id: 3},
  {permiso_id: 101, rol_id: 3},
  {permiso_id: 80, rol_id: 4},
  {permiso_id: 101, rol_id: 4},
  {permiso_id: 121, rol_id: 3},
  {permiso_id: 37, rol_id: 1},
  {permiso_id: 38, rol_id: 1},
  {permiso_id: 39, rol_id: 1},
  {permiso_id: 40, rol_id: 1},
  {permiso_id: 111, rol_id: 1},
  {permiso_id: 77, rol_id: 1},
  {permiso_id: 78, rol_id: 1},
  {permiso_id: 79, rol_id: 1},
  {permiso_id: 80, rol_id: 1},
  {permiso_id: 101, rol_id: 1},
  {permiso_id: 121, rol_id: 1}
])

User.create!([
  {email: "valeriianaa@gmail.com", password: "12345678", encrypted_password: "$2a$11$IOIqTifJSSss5Ux4qvnwyet8eVOAXbLnDdygO/WWLL3gpl8eW7Bhu", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, persona_id: 1, rol_id: 2},
  {email: "luiscastro@gmail.com", password: "12345678", encrypted_password: "$2a$11$uFat0oc4vonnYiRH71Egde1ZjZ7jIQdFNyb9vLL0jOTtZfNhEJEFq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, persona_id: 6, rol_id: 3},
  {email: "mq@gmail.com", password: "12345678", encrypted_password: "$2a$11$ozq2DVoT.jkbDsKalmbklOAtl6RElAHDuglwK0D/RVIinX/hIa2.m", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, persona_id: 2, rol_id: 1}
])